### PR TITLE
FileDropZone characteristic usage

### PR DESCRIPTION
**Pull request by libertymayc**

### CODE REVIEW

**Review by origami-z — DISMISSED** [review]
Do we need backward comp?

**Comment by origami-z** [comment]
Should file dropzone have hover color at all ? I thought it's only the button needed.

file dropzone hover

**Comment by origami-z** [comment]
So change of color on hover normally means interactivity, but clicking the light blue area doesn't do anything. Are we sure that's what we want?

**Comment by libertymayc** [comment]
maybe it makes sense to have it when something is actively being dragged in. can we detect that? @origami-z

**Comment by origami-z** [comment]
Not sure the best way to handle it, but listening to drag events and add class would do?

**Review by origami-z — APPROVED** [review]

**Review by origami-z — DISMISSED** [review]

**Review by heswell — DISMISSED** [review]

**Review by joshwooding — CHANGES_REQUESTED** [review]
I'm seeing some weird flickering when hovering over the drop zone with a file

**Review by joshwooding — DISMISSED** [review]
Raised https://github.com/jpmorganchase/uitk/issues/279 for the flickering issue but everything else looks good

**Review by joshwooding — APPROVED** [review]

**Pull request merged**
